### ISSUE TITLE
Could not find openssl on your system on this path

### ISSUE THREAD

**Issue by Mr-Chilly** [dYb/grunt-ftps-deploy#1]
I have a standard config, taken from grunt-ftp-deploy which worked perfectly, and then added the 'secure:true'

'ftps_deploy': {
            build: {
                auth: {
                  host: '88.150.163.159',
                  port: 21,
                  authKey: 'key1',
                  secure: true  
                },
            src: '<%= paths.dist %>',
            dest: '<%= paths.livefolder %>/<%= paths.mainfolder %>/<%= paths.finalemail %>',
            exclusions: ['<%= paths.dist %>/**/.DS_Store', '<%= paths.dist %>/**/Thumbs.db', '<%= paths.dist %>/tmp'],
            }
        },  

Which produces this:

Running "ftps_deploy:build" (ftps_deploy) task
Verifying property ftps_deploy.build exists in config...OK
Files: dist -> local-b2g/newsletter/f-index
Options: auth={"host":"0.0.0.0","port":3000,"authKey":"key1","secure":false}
Reading .ftppass...OK
[Error: Could not find openssl on your system on this path: openssl]
Fatal error: connect EADDRNOTAVAIL

Fingers crossed this is easy to fix

**Comment by dYb** [comment]
yep,  need for openssl

**Comment by Mr-Chilly** [comment]
is there a way to specify the path to opensll? I Don't really want an .exe
in root of my projects, or better yet, bundle it into the grunt
dependencies?

**Comment by dYb** [comment]
u can add your openssl path to `environment variables`
