### ISSUE TITLE
What does "expand" and "cwd" mean? Can you exclude files and folders?

### ISSUE THREAD

**Issue by JacobLett** [dYb/grunt-ftps-deploy#2]
Trying to configure this but not sure what these options mean. 

expand: true,
cwd:'app',

I was using https://www.npmjs.com/package/grunt-ftp-deploy but recently the server needed TLS. 

Thank you for your help.

**Comment by dYb** [comment]
These options are just common grunt task config. you can check it on [this page](http://gruntjs.com/configuring-tasks#files)  

```
files: [
        {
          expand: true,     // Enable dynamic expansion.
          cwd: 'lib/',      // Src matches are relative to this path.
          src: ['**/*.js'], // Actual pattern(s) to match.
          dest: 'build/',   // Destination path prefix.
          ext: '.min.js',   // Dest filepaths will have this extension.
          extDot: 'first'   // Extensions in filenames begin after the first dot
        },
]
```

> expand Set to true to enable the following options:
> - `cwd` All src matches are relative to (but don't include) this path.
> - `src` Pattern(s) to match, relative to the cwd.
> - `dest` Destination path prefix.
> - `ext` Replace any existing extension with this value in generated dest paths.
> - `extDot` Used to indicate where the period indicating the extension is located. Can take either 'first' (extension begins after the first period in the file name) or 'last' (extension begins after the last period), and is set by default to 'first' [Added in 0.4.3]
> - `flatten` Remove all path parts from generated dest paths.
> - `rename` This function is called for each matched src file, (after extension renaming and flattening). The dest and matched src path are passed in, and this function must return a new dest value. If the same dest is returned more than once, each src which used it will be added to an array of sources for it.

And if you want to exclude some files ,you can use `!`, for example:

```
// All files except for bar.js, in alpha order:
{src: ['foo/*.js', '!foo/bar.js'], dest: ...}
```

The above are all from gruntjs.com
